import type { Stylist } from "@/types";

// headshot: set to a path under /public/stylists/<name>.jpg when real photos are available.
// Leave undefined to show the styled initials fallback in StylistCard.
export const STYLISTS: Stylist[] = [
  {
    id: "laci",
    name: "Laci",
    level: "senior",
    title: "Owner & Senior Colorist",
    bio: "Laci founded The Salty Mane with a passion for transformative color and healthy hair. Specializing in dramatic blonde journeys, color correction, and hand-tied extensions, she brings both artistry and hair science to every appointment.",
    specialties: ["Blonde Transformations", "Color Correction", "Hand-Tied Extensions", "Hair Restoration"],
    tags: ["blonde", "color-correction", "extensions", "repair", "balayage"],
    extensionCertified: true,
    colorCorrectionEligible: true,
    maxComplexPerDay: 2,
    maxTotalSlotsPerDay: 4,
    instagram: "@the.salty.mane",
    // headshot: "/stylists/laci.jpg",
  },
  {
    id: "olivia",
    name: "Olivia",
    level: "senior",
    title: "Blonde & Color Specialist",
    bio: "Olivia is our in-house blonde expert with a gift for creating dimensional, lived-in color that looks effortless. From sun-kissed highlights to full balayage transformations, Olivia ensures your hair stays as healthy as it is beautiful.",
    specialties: ["Balayage", "Highlights", "Blonde Maintenance", "Hair Restoration"],
    tags: ["blonde", "balayage", "highlights", "extensions", "repair", "keratin"],
    extensionCertified: true,
    colorCorrectionEligible: false,
    maxComplexPerDay: 3,
    maxTotalSlotsPerDay: 5,
    // headshot: "/stylists/olivia.jpg",
  },
  {
    id: "grace",
    name: "Grace",
    level: "mid-senior",
    title: "Color & Cut Artist",
    bio: "Grace has a rare talent for precision cuts that grow out beautifully and lived-in color that looks natural. Her calm energy and exceptional communication make her a favorite among clients who want to feel truly heard and understood.",
    specialties: ["Precision Cuts", "Lived-In Color", "Highlights", "Tones & Glosses"],
    tags: ["cuts", "balayage", "highlights", "tones"],
    extensionCertified: false,
    colorCorrectionEligible: false,
    maxComplexPerDay: 3,
    maxTotalSlotsPerDay: 5,
    // headshot: "/stylists/grace.jpg",
  },
  {
    id: "erica",
    name: "Erica",
    level: "mid-senior",
    title: "Blonde, Balayage & Extensions",
    bio: "Erica lives for the perfect blonde. Whether you're dreaming of platinum, honey, or buttery balayage, she has the eye and the technique to get you there — while keeping your hair in its healthiest state. Extension specialist with a loyal clientele.",
    specialties: ["Blonde", "Balayage", "Hair Extensions", "Highlights"],
    tags: ["blonde", "balayage", "highlights", "extensions"],
    extensionCertified: true,
    colorCorrectionEligible: false,
    maxComplexPerDay: 3,
    maxTotalSlotsPerDay: 5,
    instagram: "@ericaa.mane",
    // headshot: "/stylists/erica.jpg",
  },
  {
    id: "reese",
    name: "Reese",
    level: "mid-senior",
    title: "Hairstylist",
    bio: "Reese brings fresh energy and a sharp eye for detail to every appointment. Known for her seamless color work and client-first approach, she's quickly become a go-to for clients who want both great results and a great experience in the chair.",
    specialties: ["Color", "Cuts", "Highlights", "Blowouts"],
    tags: ["cuts", "highlights", "balayage", "tones", "blowouts"],
    extensionCertified: false,
    colorCorrectionEligible: false,
    maxComplexPerDay: 3,
    maxTotalSlotsPerDay: 5,
    instagram: "@reese.mane",
    // headshot: "/stylists/reese.jpg",
  },
  {
    id: "anna",
    name: "Anna",
    level: "mid",
    title: "Style & Color Expert",
    bio: "Anna's clients leave the chair feeling like the best version of themselves. With a meticulous eye for color application and a warm, confidence-building approach, Anna excels at making every visit feel personal and results feel polished.",
    specialties: ["Color Retouches", "Partial Highlights", "Haircuts", "Glosses"],
    tags: ["cuts", "highlights", "tones", "blowouts"],
    extensionCertified: false,
    colorCorrectionEligible: false,
    maxComplexPerDay: 3,
    maxTotalSlotsPerDay: 6,
    // headshot: "/stylists/anna.jpg",
  },
  {
    id: "sara",
    name: "Sara",
    level: "mid",
    title: "Styling Specialist",
    bio: "Sara's artistry shines in the details — from a perfectly blowdried blowout to a seamless event updo. She's your go-to for looking polished and camera-ready, and her maintenance color keeps clients looking fresh between major services.",
    specialties: ["Blowouts & Styling", "Event Hair", "Cuts", "Color Maintenance"],
    tags: ["cuts", "blowouts", "tones"],
    extensionCertified: false,
    colorCorrectionEligible: false,
    maxComplexPerDay: 3,
    maxTotalSlotsPerDay: 6,
    // headshot: "/stylists/sara.jpg",
  },
  {
    id: "jolie",
    name: "Jolie",
    level: "mid",
    title: "Stylist",
    bio: "Jolie is a valued member of the Salty Mane team. Update this bio with Jolie's specialties and personality — ask Laci for details or pull from her Instagram.",
    specialties: ["Cuts", "Color", "Styling"],
    tags: ["cuts", "tones", "blowouts"],
    extensionCertified: false,
    colorCorrectionEligible: false,
    maxComplexPerDay: 3,
    maxTotalSlotsPerDay: 6,
    // headshot: "/stylists/jolie.jpg",
  },
];

export function getStylistById(id: string): Stylist | undefined {
  return STYLISTS.find((s) => s.id === id);
}
