import type { Stylist } from "@/types";

export const STYLISTS: Stylist[] = [
  {
    id: "laci",
    name: "Laci",
    level: "senior",
    title: "Owner & Senior Colorist",
    bio: "Laci founded The Salty Mane with a passion for transformative color and healthy hair. Specializing in dramatic blonde journeys, color correction, and hand-tied extensions, she brings both artistry and hair science to every appointment.",
    specialties: [
      "Blonde Transformations",
      "Color Correction",
      "Hand-Tied Extensions",
      "Hair Restoration",
    ],
    tags: ["blonde", "color-correction", "extensions", "repair", "balayage"],
    extensionCertified: true,
    colorCorrectionEligible: true,
    maxComplexPerDay: 2,
    maxTotalSlotsPerDay: 4,
    instagram: "@the.salty.mane",
    headshot: "https://picsum.photos/seed/laci-stylist/400/500",
  },
  {
    id: "olivia",
    name: "Olivia",
    level: "senior",
    title: "Blonde & Color Specialist",
    bio: "Olivia is our in-house blonde expert with a gift for creating dimensional, lived-in color that looks effortless. From sun-kissed highlights to full balayage transformations, Olivia ensures your hair stays as healthy as it is beautiful.",
    specialties: [
      "Balayage",
      "Highlights",
      "Blonde Maintenance",
      "Hair Restoration",
    ],
    tags: ["blonde", "balayage", "highlights", "extensions", "repair", "keratin"],
    extensionCertified: true,
    colorCorrectionEligible: false,
    maxComplexPerDay: 3,
    maxTotalSlotsPerDay: 5,
    headshot: "https://picsum.photos/seed/olivia-stylist/400/500",
  },
  {
    id: "grace",
    name: "Grace",
    level: "mid-senior",
    title: "Color & Cut Artist",
    bio: "Grace has a rare talent for precision cuts that grow out beautifully and lived-in color that looks natural. Her calm energy and exceptional communication make her a favorite among clients who want to feel truly heard and understood.",
    specialties: [
      "Precision Cuts",
      "Lived-In Color",
      "Highlights",
      "Tones & Glosses",
    ],
    tags: ["cuts", "balayage", "highlights", "tones"],
    extensionCertified: false,
    colorCorrectionEligible: false,
    maxComplexPerDay: 3,
    maxTotalSlotsPerDay: 5,
    headshot: "https://picsum.photos/seed/grace-stylist/400/500",
  },
  {
    id: "anna",
    name: "Anna",
    level: "mid",
    title: "Style & Color Expert",
    bio: "Anna's clients leave the chair feeling like the best version of themselves. With a meticulous eye for color application and a warm, confidence-building approach, Anna excels at making every visit feel personal and results feel polished.",
    specialties: [
      "Color Retouches",
      "Partial Highlights",
      "Haircuts",
      "Glosses",
    ],
    tags: ["cuts", "highlights", "tones", "blowouts"],
    extensionCertified: false,
    colorCorrectionEligible: false,
    maxComplexPerDay: 3,
    maxTotalSlotsPerDay: 6,
    headshot: "https://picsum.photos/seed/anna-stylist/400/500",
  },
  {
    id: "sara",
    name: "Sara",
    level: "mid",
    title: "Styling Specialist",
    bio: "Sara's artistry shines in the details — from a perfectly blowdried blowout to a seamless event updo. She's your go-to for looking polished and camera-ready, and her maintenance color keeps clients looking fresh between major services.",
    specialties: [
      "Blowouts & Styling",
      "Event Hair",
      "Cuts",
      "Color Maintenance",
    ],
    tags: ["cuts", "blowouts", "tones"],
    extensionCertified: false,
    colorCorrectionEligible: false,
    maxComplexPerDay: 3,
    maxTotalSlotsPerDay: 6,
    headshot: "https://picsum.photos/seed/sara-stylist/400/500",
  },
];

export function getStylistById(id: string): Stylist | undefined {
  return STYLISTS.find((s) => s.id === id);
}
